#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 136
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 6

enum {
  sym_id = 1,
  anon_sym_SEMI = 2,
  anon_sym_class = 3,
  anon_sym_inherits = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_LPAREN = 7,
  anon_sym_COMMA = 8,
  anon_sym_RPAREN = 9,
  anon_sym_COLON = 10,
  anon_sym_LT_DASH = 11,
  sym_type = 12,
  anon_sym_while = 13,
  anon_sym_loop = 14,
  anon_sym_pool = 15,
  anon_sym_case = 16,
  anon_sym_of = 17,
  anon_sym_EQ_GT = 18,
  anon_sym_esac = 19,
  anon_sym_new = 20,
  anon_sym_TILDE = 21,
  anon_sym_isvoid = 22,
  anon_sym_STAR = 23,
  anon_sym_SLASH = 24,
  anon_sym_PLUS = 25,
  anon_sym_DASH = 26,
  anon_sym_LT_EQ = 27,
  anon_sym_LT = 28,
  anon_sym_EQ = 29,
  anon_sym_not = 30,
  anon_sym_true = 31,
  anon_sym_false = 32,
  anon_sym_let = 33,
  anon_sym_in = 34,
  anon_sym_AT = 35,
  anon_sym_DOT = 36,
  anon_sym_if = 37,
  anon_sym_then = 38,
  anon_sym_else = 39,
  anon_sym_fi = 40,
  sym_int = 41,
  anon_sym_DQUOTE = 42,
  aux_sym_string_token1 = 43,
  sym_comment = 44,
  sym_program = 45,
  sym_classDefine = 46,
  sym_feature = 47,
  sym_method = 48,
  sym_property = 49,
  sym_formal = 50,
  sym_expr = 51,
  sym_dispatch = 52,
  sym_functionCall = 53,
  sym_if = 54,
  sym_string = 55,
  aux_sym_program_repeat1 = 56,
  aux_sym_classDefine_repeat1 = 57,
  aux_sym_method_repeat1 = 58,
  aux_sym_expr_repeat1 = 59,
  aux_sym_expr_repeat2 = 60,
  aux_sym_expr_repeat3 = 61,
  aux_sym_dispatch_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_id] = "id",
  [anon_sym_SEMI] = ";",
  [anon_sym_class] = "class",
  [anon_sym_inherits] = "inherits",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LT_DASH] = "<-",
  [sym_type] = "type",
  [anon_sym_while] = "while",
  [anon_sym_loop] = "loop",
  [anon_sym_pool] = "pool",
  [anon_sym_case] = "case",
  [anon_sym_of] = "of",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_esac] = "esac",
  [anon_sym_new] = "new",
  [anon_sym_TILDE] = "~",
  [anon_sym_isvoid] = "isvoid",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT] = "<",
  [anon_sym_EQ] = "=",
  [anon_sym_not] = "not",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_let] = "let",
  [anon_sym_in] = "in",
  [anon_sym_AT] = "@",
  [anon_sym_DOT] = ".",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_fi] = "fi",
  [sym_int] = "int",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym_classDefine] = "classDefine",
  [sym_feature] = "feature",
  [sym_method] = "method",
  [sym_property] = "property",
  [sym_formal] = "formal",
  [sym_expr] = "expr",
  [sym_dispatch] = "dispatch",
  [sym_functionCall] = "functionCall",
  [sym_if] = "if",
  [sym_string] = "string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_classDefine_repeat1] = "classDefine_repeat1",
  [aux_sym_method_repeat1] = "method_repeat1",
  [aux_sym_expr_repeat1] = "expr_repeat1",
  [aux_sym_expr_repeat2] = "expr_repeat2",
  [aux_sym_expr_repeat3] = "expr_repeat3",
  [aux_sym_dispatch_repeat1] = "dispatch_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_id] = sym_id,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_inherits] = anon_sym_inherits,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [sym_type] = sym_type,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_pool] = anon_sym_pool,
  [anon_sym_case] = anon_sym_case,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_esac] = anon_sym_esac,
  [anon_sym_new] = anon_sym_new,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_isvoid] = anon_sym_isvoid,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_fi] = anon_sym_fi,
  [sym_int] = sym_int,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym_classDefine] = sym_classDefine,
  [sym_feature] = sym_feature,
  [sym_method] = sym_method,
  [sym_property] = sym_property,
  [sym_formal] = sym_formal,
  [sym_expr] = sym_expr,
  [sym_dispatch] = sym_dispatch,
  [sym_functionCall] = sym_functionCall,
  [sym_if] = sym_if,
  [sym_string] = sym_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_classDefine_repeat1] = aux_sym_classDefine_repeat1,
  [aux_sym_method_repeat1] = aux_sym_method_repeat1,
  [aux_sym_expr_repeat1] = aux_sym_expr_repeat1,
  [aux_sym_expr_repeat2] = aux_sym_expr_repeat2,
  [aux_sym_expr_repeat3] = aux_sym_expr_repeat3,
  [aux_sym_dispatch_repeat1] = aux_sym_dispatch_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inherits] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_case] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_esac] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_new] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isvoid] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fi] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_classDefine] = {
    .visible = true,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_formal] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_dispatch] = {
    .visible = true,
    .named = true,
  },
  [sym_functionCall] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_classDefine_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_method_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expr_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expr_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dispatch_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_condition = 2,
  field_else = 3,
  field_name = 4,
  field_then = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_condition] = "condition",
  [field_else] = "else",
  [field_name] = "name",
  [field_then] = "then",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_body, 3},
    {field_condition, 1},
  [3] =
    {field_name, 2},
  [4] =
    {field_condition, 1},
    {field_else, 5},
    {field_then, 3},
  [7] =
    {field_name, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == '@') ADVANCE(34);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '~') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '@') ADVANCE(34);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '@') ADVANCE(34);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(9);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(45);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(46);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '*') ADVANCE(7);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(46);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '"') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(8);
      if (lookahead == 't') ADVANCE(9);
      if (lookahead == 'w') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(26);
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_fi);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 'h') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'v') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'w') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 37:
      if (lookahead == 'p') ADVANCE(51);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_new);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_case);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_esac);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_pool);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 59:
      if (lookahead == 'd') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_isvoid);
      END_STATE();
    case 63:
      if (lookahead == 's') ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_inherits);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 4},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 41},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_inherits] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_pool] = ACTIONS(1),
    [anon_sym_case] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_esac] = ACTIONS(1),
    [anon_sym_new] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_isvoid] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_fi] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(122),
    [sym_classDefine] = STATE(104),
    [aux_sym_program_repeat1] = STATE(78),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_class] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LT_DASH,
    ACTIONS(15), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(9), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [34] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_id,
    ACTIONS(20), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(28), 1,
      anon_sym_while,
    ACTIONS(31), 1,
      anon_sym_case,
    ACTIONS(34), 1,
      anon_sym_new,
    ACTIONS(37), 1,
      anon_sym_TILDE,
    ACTIONS(46), 1,
      anon_sym_let,
    ACTIONS(49), 1,
      anon_sym_if,
    ACTIONS(52), 1,
      sym_int,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      aux_sym_expr_repeat1,
    STATE(64), 1,
      sym_expr,
    ACTIONS(40), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [94] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      aux_sym_expr_repeat1,
    STATE(64), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [154] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [211] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [268] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [325] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      aux_sym_expr_repeat1,
    STATE(64), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [382] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(57), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [436] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(92), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [464] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(96), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [492] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [546] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(100), 13,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [582] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(110), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [610] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(114), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [638] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(118), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [666] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [720] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(122), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [748] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(126), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [776] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [830] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(66), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [884] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(132), 1,
      anon_sym_LT,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(130), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [918] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(132), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(130), 16,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [948] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(134), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [976] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1030] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(52), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1084] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(23), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1138] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1192] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(138), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1220] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(63), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1274] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(130), 13,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1310] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(142), 13,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1346] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(130), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1374] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(142), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1402] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(61), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1456] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1510] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1564] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1618] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1672] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(9), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1700] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(146), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1728] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1782] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(150), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1810] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(31), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1864] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1918] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(154), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1946] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_id,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_while,
    ACTIONS(68), 1,
      anon_sym_case,
    ACTIONS(70), 1,
      anon_sym_new,
    ACTIONS(72), 1,
      anon_sym_TILDE,
    ACTIONS(78), 1,
      anon_sym_let,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(82), 1,
      sym_int,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    STATE(56), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(76), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [2000] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(150), 13,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [2036] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(158), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [2064] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_TILDE,
      sym_int,
      anon_sym_DQUOTE,
    ACTIONS(162), 11,
      anon_sym_LPAREN,
      sym_id,
      anon_sym_while,
      anon_sym_case,
      anon_sym_new,
      anon_sym_isvoid,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
  [2088] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    STATE(81), 1,
      aux_sym_dispatch_repeat1,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2124] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(172), 3,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_in,
  [2156] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_dispatch_repeat1,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2192] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_dispatch_repeat1,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2228] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(178), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2259] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(180), 1,
      anon_sym_fi,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2289] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2319] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(184), 1,
      anon_sym_then,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2349] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(186), 1,
      anon_sym_SEMI,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2379] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(188), 1,
      anon_sym_of,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2409] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_RPAREN,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2439] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(190), 1,
      anon_sym_loop,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2469] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(192), 1,
      anon_sym_pool,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2499] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(194), 1,
      anon_sym_SEMI,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2529] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(196), 1,
      anon_sym_else,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2559] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2589] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_PLUS,
    ACTIONS(106), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_AT,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(102), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2619] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_id,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_classDefine_repeat1,
    STATE(79), 1,
      sym_formal,
    STATE(130), 1,
      sym_feature,
    STATE(129), 2,
      sym_method,
      sym_property,
  [2642] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_id,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_classDefine_repeat1,
    STATE(79), 1,
      sym_formal,
    STATE(130), 1,
      sym_feature,
    STATE(129), 2,
      sym_method,
      sym_property,
  [2665] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_id,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_classDefine_repeat1,
    STATE(79), 1,
      sym_formal,
    STATE(130), 1,
      sym_feature,
    STATE(129), 2,
      sym_method,
      sym_property,
  [2688] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_id,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym_classDefine_repeat1,
    STATE(79), 1,
      sym_formal,
    STATE(130), 1,
      sym_feature,
    STATE(129), 2,
      sym_method,
      sym_property,
  [2711] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym_id,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_classDefine_repeat1,
    STATE(79), 1,
      sym_formal,
    STATE(130), 1,
      sym_feature,
    STATE(129), 2,
      sym_method,
      sym_property,
  [2734] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_EQ_GT,
      anon_sym_in,
  [2746] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_id,
    ACTIONS(221), 1,
      anon_sym_esac,
    STATE(77), 1,
      aux_sym_expr_repeat2,
    STATE(103), 1,
      sym_formal,
  [2762] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_in,
    ACTIONS(219), 1,
      sym_id,
    STATE(79), 1,
      sym_formal,
    STATE(92), 1,
      sym_property,
  [2778] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(225), 1,
      anon_sym_class,
    STATE(76), 1,
      aux_sym_program_repeat1,
    STATE(104), 1,
      sym_classDefine,
  [2794] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_id,
    ACTIONS(231), 1,
      anon_sym_esac,
    STATE(77), 1,
      aux_sym_expr_repeat2,
    STATE(103), 1,
      sym_formal,
  [2810] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_class,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
    STATE(76), 1,
      aux_sym_program_repeat1,
    STATE(104), 1,
      sym_classDefine,
  [2826] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LT_DASH,
    ACTIONS(235), 3,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_in,
  [2838] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_method_repeat1,
  [2851] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_dispatch_repeat1,
  [2864] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_id,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      sym_formal,
  [2877] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    STATE(83), 1,
      aux_sym_dispatch_repeat1,
  [2890] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_in,
    STATE(91), 1,
      aux_sym_expr_repeat3,
  [2903] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_id,
    STATE(79), 1,
      sym_formal,
    STATE(95), 1,
      sym_property,
  [2916] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_dispatch_repeat1,
  [2929] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_id,
    STATE(74), 1,
      aux_sym_expr_repeat2,
    STATE(103), 1,
      sym_formal,
  [2942] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_method_repeat1,
  [2955] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_method_repeat1,
  [2968] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_dispatch_repeat1,
  [2981] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_in,
    STATE(91), 1,
      aux_sym_expr_repeat3,
  [2994] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_in,
    STATE(84), 1,
      aux_sym_expr_repeat3,
  [3007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [3015] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_inherits,
    ACTIONS(276), 1,
      anon_sym_LBRACE,
  [3025] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 2,
      anon_sym_COMMA,
      anon_sym_in,
  [3033] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_LPAREN,
    ACTIONS(280), 1,
      anon_sym_COLON,
  [3043] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 2,
      sym_id,
      anon_sym_esac,
  [3051] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 2,
      anon_sym_RBRACE,
      sym_id,
  [3059] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_id,
    STATE(93), 1,
      sym_formal,
  [3069] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 2,
      ts_builtin_sym_end,
      anon_sym_class,
  [3077] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_LPAREN,
  [3084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_SEMI,
  [3091] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_EQ_GT,
  [3098] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_SEMI,
  [3105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_LBRACE,
  [3112] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_COLON,
  [3119] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      sym_type,
  [3126] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      sym_type,
  [3133] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_LBRACE,
  [3140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym_id,
  [3147] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      sym_type,
  [3154] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_DQUOTE,
  [3161] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_COLON,
  [3168] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      sym_type,
  [3175] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_DOT,
  [3182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      sym_type,
  [3189] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      anon_sym_SEMI,
  [3196] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      sym_id,
  [3203] = 2,
    ACTIONS(320), 1,
      aux_sym_string_token1,
    ACTIONS(322), 1,
      sym_comment,
  [3210] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      sym_type,
  [3217] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_COLON,
  [3224] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      ts_builtin_sym_end,
  [3231] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_COLON,
  [3238] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      anon_sym_SEMI,
  [3245] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      anon_sym_SEMI,
  [3252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_LBRACE,
  [3259] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      anon_sym_SEMI,
  [3266] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym_type,
  [3273] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      anon_sym_SEMI,
  [3280] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_SEMI,
  [3287] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      anon_sym_LPAREN,
  [3294] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      anon_sym_SEMI,
  [3301] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_SEMI,
  [3308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      anon_sym_LBRACE,
  [3315] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      sym_type,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 154,
  [SMALL_STATE(6)] = 211,
  [SMALL_STATE(7)] = 268,
  [SMALL_STATE(8)] = 325,
  [SMALL_STATE(9)] = 382,
  [SMALL_STATE(10)] = 436,
  [SMALL_STATE(11)] = 464,
  [SMALL_STATE(12)] = 492,
  [SMALL_STATE(13)] = 546,
  [SMALL_STATE(14)] = 582,
  [SMALL_STATE(15)] = 610,
  [SMALL_STATE(16)] = 638,
  [SMALL_STATE(17)] = 666,
  [SMALL_STATE(18)] = 720,
  [SMALL_STATE(19)] = 748,
  [SMALL_STATE(20)] = 776,
  [SMALL_STATE(21)] = 830,
  [SMALL_STATE(22)] = 884,
  [SMALL_STATE(23)] = 918,
  [SMALL_STATE(24)] = 948,
  [SMALL_STATE(25)] = 976,
  [SMALL_STATE(26)] = 1030,
  [SMALL_STATE(27)] = 1084,
  [SMALL_STATE(28)] = 1138,
  [SMALL_STATE(29)] = 1192,
  [SMALL_STATE(30)] = 1220,
  [SMALL_STATE(31)] = 1274,
  [SMALL_STATE(32)] = 1310,
  [SMALL_STATE(33)] = 1346,
  [SMALL_STATE(34)] = 1374,
  [SMALL_STATE(35)] = 1402,
  [SMALL_STATE(36)] = 1456,
  [SMALL_STATE(37)] = 1510,
  [SMALL_STATE(38)] = 1564,
  [SMALL_STATE(39)] = 1618,
  [SMALL_STATE(40)] = 1672,
  [SMALL_STATE(41)] = 1700,
  [SMALL_STATE(42)] = 1728,
  [SMALL_STATE(43)] = 1782,
  [SMALL_STATE(44)] = 1810,
  [SMALL_STATE(45)] = 1864,
  [SMALL_STATE(46)] = 1918,
  [SMALL_STATE(47)] = 1946,
  [SMALL_STATE(48)] = 2000,
  [SMALL_STATE(49)] = 2036,
  [SMALL_STATE(50)] = 2064,
  [SMALL_STATE(51)] = 2088,
  [SMALL_STATE(52)] = 2124,
  [SMALL_STATE(53)] = 2156,
  [SMALL_STATE(54)] = 2192,
  [SMALL_STATE(55)] = 2228,
  [SMALL_STATE(56)] = 2259,
  [SMALL_STATE(57)] = 2289,
  [SMALL_STATE(58)] = 2319,
  [SMALL_STATE(59)] = 2349,
  [SMALL_STATE(60)] = 2379,
  [SMALL_STATE(61)] = 2409,
  [SMALL_STATE(62)] = 2439,
  [SMALL_STATE(63)] = 2469,
  [SMALL_STATE(64)] = 2499,
  [SMALL_STATE(65)] = 2529,
  [SMALL_STATE(66)] = 2559,
  [SMALL_STATE(67)] = 2589,
  [SMALL_STATE(68)] = 2619,
  [SMALL_STATE(69)] = 2642,
  [SMALL_STATE(70)] = 2665,
  [SMALL_STATE(71)] = 2688,
  [SMALL_STATE(72)] = 2711,
  [SMALL_STATE(73)] = 2734,
  [SMALL_STATE(74)] = 2746,
  [SMALL_STATE(75)] = 2762,
  [SMALL_STATE(76)] = 2778,
  [SMALL_STATE(77)] = 2794,
  [SMALL_STATE(78)] = 2810,
  [SMALL_STATE(79)] = 2826,
  [SMALL_STATE(80)] = 2838,
  [SMALL_STATE(81)] = 2851,
  [SMALL_STATE(82)] = 2864,
  [SMALL_STATE(83)] = 2877,
  [SMALL_STATE(84)] = 2890,
  [SMALL_STATE(85)] = 2903,
  [SMALL_STATE(86)] = 2916,
  [SMALL_STATE(87)] = 2929,
  [SMALL_STATE(88)] = 2942,
  [SMALL_STATE(89)] = 2955,
  [SMALL_STATE(90)] = 2968,
  [SMALL_STATE(91)] = 2981,
  [SMALL_STATE(92)] = 2994,
  [SMALL_STATE(93)] = 3007,
  [SMALL_STATE(94)] = 3015,
  [SMALL_STATE(95)] = 3025,
  [SMALL_STATE(96)] = 3033,
  [SMALL_STATE(97)] = 3043,
  [SMALL_STATE(98)] = 3051,
  [SMALL_STATE(99)] = 3059,
  [SMALL_STATE(100)] = 3069,
  [SMALL_STATE(101)] = 3077,
  [SMALL_STATE(102)] = 3084,
  [SMALL_STATE(103)] = 3091,
  [SMALL_STATE(104)] = 3098,
  [SMALL_STATE(105)] = 3105,
  [SMALL_STATE(106)] = 3112,
  [SMALL_STATE(107)] = 3119,
  [SMALL_STATE(108)] = 3126,
  [SMALL_STATE(109)] = 3133,
  [SMALL_STATE(110)] = 3140,
  [SMALL_STATE(111)] = 3147,
  [SMALL_STATE(112)] = 3154,
  [SMALL_STATE(113)] = 3161,
  [SMALL_STATE(114)] = 3168,
  [SMALL_STATE(115)] = 3175,
  [SMALL_STATE(116)] = 3182,
  [SMALL_STATE(117)] = 3189,
  [SMALL_STATE(118)] = 3196,
  [SMALL_STATE(119)] = 3203,
  [SMALL_STATE(120)] = 3210,
  [SMALL_STATE(121)] = 3217,
  [SMALL_STATE(122)] = 3224,
  [SMALL_STATE(123)] = 3231,
  [SMALL_STATE(124)] = 3238,
  [SMALL_STATE(125)] = 3245,
  [SMALL_STATE(126)] = 3252,
  [SMALL_STATE(127)] = 3259,
  [SMALL_STATE(128)] = 3266,
  [SMALL_STATE(129)] = 3273,
  [SMALL_STATE(130)] = 3280,
  [SMALL_STATE(131)] = 3287,
  [SMALL_STATE(132)] = 3294,
  [SMALL_STATE(133)] = 3301,
  [SMALL_STATE(134)] = 3308,
  [SMALL_STATE(135)] = 3315,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(2),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expr_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(35),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(36),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(37),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(120),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(39),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(39),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(40),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(75),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(42),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(40),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(119),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 5, .production_id = 1),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functionCall, 5, .production_id = 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 9, .production_id = 5),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 9, .production_id = 5),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 4),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 4, .production_id = 1),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functionCall, 4, .production_id = 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 8, .production_id = 5),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 8, .production_id = 5),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 7, .production_id = 3),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 7, .production_id = 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 7, .production_id = 5),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 7, .production_id = 5),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 7, .production_id = 4),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 7, .production_id = 4),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 3),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 6, .production_id = 3),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 6, .production_id = 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 2),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 3, .production_id = 1),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functionCall, 3, .production_id = 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 5),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 5),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 5, .production_id = 3),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 5, .production_id = 3),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 5, .production_id = 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 5, .production_id = 2),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dispatch_repeat1, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_classDefine_repeat1, 2), SHIFT_REPEAT(96),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_classDefine_repeat1, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal, 3),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(108),
  [228] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expr_repeat2, 2), SHIFT_REPEAT(121),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expr_repeat2, 2),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 1),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dispatch_repeat1, 2), SHIFT_REPEAT(20),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 2), SHIFT_REPEAT(99),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 2),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [267] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expr_repeat3, 2), SHIFT_REPEAT(85),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expr_repeat3, 2),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [278] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expr_repeat2, 4),
  [284] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classDefine, 7),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 8, .production_id = 1),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [320] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [322] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [326] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classDefine, 6),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 9, .production_id = 1),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classDefine, 5),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 1),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [344] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 10, .production_id = 1),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classDefine, 4),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cool(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_id,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
