#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 135
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 4

enum {
  sym_id = 1,
  anon_sym_SEMI = 2,
  anon_sym_class = 3,
  anon_sym_inherits = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_LPAREN = 7,
  anon_sym_COMMA = 8,
  anon_sym_RPAREN = 9,
  anon_sym_COLON = 10,
  anon_sym_LT_DASH = 11,
  sym_type = 12,
  anon_sym_while = 13,
  anon_sym_loop = 14,
  anon_sym_pool = 15,
  anon_sym_case = 16,
  anon_sym_of = 17,
  anon_sym_EQ_GT = 18,
  anon_sym_esac = 19,
  anon_sym_new = 20,
  anon_sym_TILDE = 21,
  anon_sym_isvoid = 22,
  anon_sym_STAR = 23,
  anon_sym_SLASH = 24,
  anon_sym_PLUS = 25,
  anon_sym_DASH = 26,
  anon_sym_LT_EQ = 27,
  anon_sym_LT = 28,
  anon_sym_EQ = 29,
  anon_sym_not = 30,
  anon_sym_true = 31,
  anon_sym_false = 32,
  anon_sym_let = 33,
  anon_sym_in = 34,
  anon_sym_AT = 35,
  anon_sym_DOT = 36,
  anon_sym_if = 37,
  anon_sym_then = 38,
  anon_sym_else = 39,
  anon_sym_fi = 40,
  sym_int = 41,
  anon_sym_DQUOTE = 42,
  aux_sym_string_token1 = 43,
  sym_comment = 44,
  sym_program = 45,
  sym_classDefine = 46,
  sym_feature = 47,
  sym_method = 48,
  sym_property = 49,
  sym_formal = 50,
  sym_expression = 51,
  sym_dispatch = 52,
  sym_functionCall = 53,
  sym_if = 54,
  sym_string = 55,
  aux_sym_program_repeat1 = 56,
  aux_sym_classDefine_repeat1 = 57,
  aux_sym_method_repeat1 = 58,
  aux_sym_expression_repeat1 = 59,
  aux_sym_expression_repeat2 = 60,
  aux_sym_expression_repeat3 = 61,
  aux_sym_dispatch_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_id] = "id",
  [anon_sym_SEMI] = ";",
  [anon_sym_class] = "class",
  [anon_sym_inherits] = "inherits",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LT_DASH] = "<-",
  [sym_type] = "type",
  [anon_sym_while] = "while",
  [anon_sym_loop] = "loop",
  [anon_sym_pool] = "pool",
  [anon_sym_case] = "case",
  [anon_sym_of] = "of",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_esac] = "esac",
  [anon_sym_new] = "new",
  [anon_sym_TILDE] = "~",
  [anon_sym_isvoid] = "isvoid",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT] = "<",
  [anon_sym_EQ] = "=",
  [anon_sym_not] = "not",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_let] = "let",
  [anon_sym_in] = "in",
  [anon_sym_AT] = "@",
  [anon_sym_DOT] = ".",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_fi] = "fi",
  [sym_int] = "int",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym_classDefine] = "classDefine",
  [sym_feature] = "feature",
  [sym_method] = "method",
  [sym_property] = "property",
  [sym_formal] = "formal",
  [sym_expression] = "expression",
  [sym_dispatch] = "dispatch",
  [sym_functionCall] = "functionCall",
  [sym_if] = "if",
  [sym_string] = "string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_classDefine_repeat1] = "classDefine_repeat1",
  [aux_sym_method_repeat1] = "method_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_expression_repeat2] = "expression_repeat2",
  [aux_sym_expression_repeat3] = "expression_repeat3",
  [aux_sym_dispatch_repeat1] = "dispatch_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_id] = sym_id,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_inherits] = anon_sym_inherits,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [sym_type] = sym_type,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_pool] = anon_sym_pool,
  [anon_sym_case] = anon_sym_case,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_esac] = anon_sym_esac,
  [anon_sym_new] = anon_sym_new,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_isvoid] = anon_sym_isvoid,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_fi] = anon_sym_fi,
  [sym_int] = sym_int,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym_classDefine] = sym_classDefine,
  [sym_feature] = sym_feature,
  [sym_method] = sym_method,
  [sym_property] = sym_property,
  [sym_formal] = sym_formal,
  [sym_expression] = sym_expression,
  [sym_dispatch] = sym_dispatch,
  [sym_functionCall] = sym_functionCall,
  [sym_if] = sym_if,
  [sym_string] = sym_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_classDefine_repeat1] = aux_sym_classDefine_repeat1,
  [aux_sym_method_repeat1] = aux_sym_method_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_expression_repeat2] = aux_sym_expression_repeat2,
  [aux_sym_expression_repeat3] = aux_sym_expression_repeat3,
  [aux_sym_dispatch_repeat1] = aux_sym_dispatch_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inherits] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_case] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_esac] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_new] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isvoid] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fi] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_classDefine] = {
    .visible = true,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_formal] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_dispatch] = {
    .visible = true,
    .named = true,
  },
  [sym_functionCall] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_classDefine_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_method_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dispatch_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 2},
  [2] =
    {field_name, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == '@') ADVANCE(34);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '~') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '@') ADVANCE(34);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '@') ADVANCE(34);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(9);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(45);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(46);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '*') ADVANCE(7);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(46);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '"') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(8);
      if (lookahead == 't') ADVANCE(9);
      if (lookahead == 'w') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(26);
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_fi);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 'h') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'v') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'w') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 37:
      if (lookahead == 'p') ADVANCE(51);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_new);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_case);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_esac);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_pool);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 59:
      if (lookahead == 'd') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_isvoid);
      END_STATE();
    case 63:
      if (lookahead == 's') ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_inherits);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 41},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 4},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_inherits] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_pool] = ACTIONS(1),
    [anon_sym_case] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_esac] = ACTIONS(1),
    [anon_sym_new] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_isvoid] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_fi] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(134),
    [sym_classDefine] = STATE(132),
    [aux_sym_program_repeat1] = STATE(74),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_class] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_id,
    ACTIONS(12), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(20), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_case,
    ACTIONS(26), 1,
      anon_sym_new,
    ACTIONS(29), 1,
      anon_sym_TILDE,
    ACTIONS(38), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_if,
    ACTIONS(44), 1,
      sym_int,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_expression_repeat1,
    STATE(66), 1,
      sym_expression,
    ACTIONS(32), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [60] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_RBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_expression_repeat1,
    STATE(66), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [120] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT_DASH,
    ACTIONS(84), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(78), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [154] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      aux_sym_expression_repeat1,
    STATE(66), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [211] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [268] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [325] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [382] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(92), 13,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [418] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(54), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [472] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(104), 1,
      anon_sym_LT,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(102), 15,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [506] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(106), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [534] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(110), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [562] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [616] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(114), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [644] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [698] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [752] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(102), 13,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [788] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(46), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [842] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(118), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [870] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [924] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(122), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [952] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(11), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1006] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(51), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1060] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(126), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1088] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(102), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1116] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(63), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1170] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1224] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(130), 13,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1260] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(56), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1314] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1368] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(132), 13,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1404] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(57), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1458] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(61), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1512] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1566] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(130), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1594] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(9), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1648] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(78), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1676] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(136), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1704] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1758] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(140), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1786] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(144), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(148), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1842] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [1896] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(152), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1924] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(104), 1,
      anon_sym_LT,
    ACTIONS(102), 17,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [1956] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_id,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_while,
    ACTIONS(60), 1,
      anon_sym_case,
    ACTIONS(62), 1,
      anon_sym_new,
    ACTIONS(64), 1,
      anon_sym_TILDE,
    ACTIONS(70), 1,
      anon_sym_let,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      sym_int,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      sym_expression,
    ACTIONS(66), 2,
      anon_sym_isvoid,
      anon_sym_not,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 4,
      sym_dispatch,
      sym_functionCall,
      sym_if,
      sym_string,
  [2010] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_LT,
    ACTIONS(92), 18,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_loop,
      anon_sym_pool,
      anon_sym_of,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_AT,
      anon_sym_DOT,
      anon_sym_then,
      anon_sym_else,
      anon_sym_fi,
  [2038] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_TILDE,
      sym_int,
      anon_sym_DQUOTE,
    ACTIONS(158), 11,
      anon_sym_LPAREN,
      sym_id,
      anon_sym_while,
      anon_sym_case,
      anon_sym_new,
      anon_sym_isvoid,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
  [2062] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    STATE(84), 1,
      aux_sym_dispatch_repeat1,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2098] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(168), 3,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_in,
  [2130] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_dispatch_repeat1,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2166] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_dispatch_repeat1,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2202] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(174), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2233] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2263] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2293] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_RPAREN,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2323] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(180), 1,
      anon_sym_then,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2353] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2383] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(184), 1,
      anon_sym_else,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2413] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(186), 1,
      anon_sym_loop,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2443] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(188), 1,
      anon_sym_of,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2473] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(190), 1,
      anon_sym_fi,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2503] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(192), 1,
      anon_sym_pool,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2533] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(194), 1,
      anon_sym_SEMI,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2563] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(164), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      anon_sym_DOT,
    ACTIONS(196), 1,
      anon_sym_SEMI,
    ACTIONS(82), 2,
      anon_sym_LT_EQ,
      anon_sym_EQ,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2593] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_id,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_classDefine_repeat1,
    STATE(75), 1,
      sym_formal,
    STATE(121), 1,
      sym_feature,
    STATE(120), 2,
      sym_method,
      sym_property,
  [2616] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_id,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_classDefine_repeat1,
    STATE(75), 1,
      sym_formal,
    STATE(121), 1,
      sym_feature,
    STATE(120), 2,
      sym_method,
      sym_property,
  [2639] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_id,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_classDefine_repeat1,
    STATE(75), 1,
      sym_formal,
    STATE(121), 1,
      sym_feature,
    STATE(120), 2,
      sym_method,
      sym_property,
  [2662] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_id,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      aux_sym_classDefine_repeat1,
    STATE(75), 1,
      sym_formal,
    STATE(121), 1,
      sym_feature,
    STATE(120), 2,
      sym_method,
      sym_property,
  [2685] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_id,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_classDefine_repeat1,
    STATE(75), 1,
      sym_formal,
    STATE(121), 1,
      sym_feature,
    STATE(120), 2,
      sym_method,
      sym_property,
  [2708] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_EQ_GT,
      anon_sym_in,
  [2720] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym_id,
    ACTIONS(218), 1,
      anon_sym_esac,
    STATE(73), 1,
      aux_sym_expression_repeat2,
    STATE(119), 1,
      sym_formal,
  [2736] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_class,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
    STATE(77), 1,
      aux_sym_program_repeat1,
    STATE(132), 1,
      sym_classDefine,
  [2752] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_LT_DASH,
    ACTIONS(222), 3,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_in,
  [2764] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_in,
    ACTIONS(226), 1,
      sym_id,
    STATE(75), 1,
      sym_formal,
    STATE(91), 1,
      sym_property,
  [2780] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      ts_builtin_sym_end,
    ACTIONS(230), 1,
      anon_sym_class,
    STATE(77), 1,
      aux_sym_program_repeat1,
    STATE(132), 1,
      sym_classDefine,
  [2796] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      sym_id,
    ACTIONS(233), 1,
      anon_sym_esac,
    STATE(73), 1,
      aux_sym_expression_repeat2,
    STATE(119), 1,
      sym_formal,
  [2812] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_in,
    STATE(79), 1,
      aux_sym_expression_repeat3,
  [2825] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_dispatch_repeat1,
  [2838] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_id,
    STATE(75), 1,
      sym_formal,
    STATE(98), 1,
      sym_property,
  [2851] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_method_repeat1,
  [2864] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_in,
    STATE(79), 1,
      aux_sym_expression_repeat3,
  [2877] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_dispatch_repeat1,
  [2890] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_dispatch_repeat1,
  [2903] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_id,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      sym_formal,
  [2916] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_dispatch_repeat1,
  [2929] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_method_repeat1,
  [2942] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_method_repeat1,
  [2955] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_id,
    STATE(78), 1,
      aux_sym_expression_repeat2,
    STATE(119), 1,
      sym_formal,
  [2968] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_in,
    STATE(83), 1,
      aux_sym_expression_repeat3,
  [2981] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_inherits,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
  [2991] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 2,
      ts_builtin_sym_end,
      anon_sym_class,
  [2999] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 2,
      sym_id,
      anon_sym_esac,
  [3007] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_LPAREN,
    ACTIONS(278), 1,
      anon_sym_COLON,
  [3017] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [3025] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 2,
      anon_sym_RBRACE,
      sym_id,
  [3033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 2,
      anon_sym_COMMA,
      anon_sym_in,
  [3041] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_id,
    STATE(96), 1,
      sym_formal,
  [3051] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_type,
  [3058] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_LBRACE,
  [3065] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym_type,
  [3072] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_DQUOTE,
  [3079] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      sym_id,
  [3086] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_COLON,
  [3093] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_LBRACE,
  [3100] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_SEMI,
  [3107] = 2,
    ACTIONS(296), 1,
      aux_sym_string_token1,
    ACTIONS(298), 1,
      sym_comment,
  [3114] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      sym_type,
  [3121] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_DOT,
  [3128] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_COLON,
  [3135] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_COLON,
  [3142] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
  [3149] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_SEMI,
  [3156] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_SEMI,
  [3163] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_SEMI,
  [3170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      sym_id,
  [3177] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_type,
  [3184] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_EQ_GT,
  [3191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_SEMI,
  [3198] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_SEMI,
  [3205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      sym_type,
  [3212] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_COLON,
  [3219] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_SEMI,
  [3226] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      anon_sym_SEMI,
  [3233] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym_type,
  [3240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_LBRACE,
  [3247] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      sym_type,
  [3254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      anon_sym_LBRACE,
  [3261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      sym_type,
  [3268] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_SEMI,
  [3275] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      anon_sym_SEMI,
  [3282] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      anon_sym_LPAREN,
  [3289] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 60,
  [SMALL_STATE(4)] = 120,
  [SMALL_STATE(5)] = 154,
  [SMALL_STATE(6)] = 211,
  [SMALL_STATE(7)] = 268,
  [SMALL_STATE(8)] = 325,
  [SMALL_STATE(9)] = 382,
  [SMALL_STATE(10)] = 418,
  [SMALL_STATE(11)] = 472,
  [SMALL_STATE(12)] = 506,
  [SMALL_STATE(13)] = 534,
  [SMALL_STATE(14)] = 562,
  [SMALL_STATE(15)] = 616,
  [SMALL_STATE(16)] = 644,
  [SMALL_STATE(17)] = 698,
  [SMALL_STATE(18)] = 752,
  [SMALL_STATE(19)] = 788,
  [SMALL_STATE(20)] = 842,
  [SMALL_STATE(21)] = 870,
  [SMALL_STATE(22)] = 924,
  [SMALL_STATE(23)] = 952,
  [SMALL_STATE(24)] = 1006,
  [SMALL_STATE(25)] = 1060,
  [SMALL_STATE(26)] = 1088,
  [SMALL_STATE(27)] = 1116,
  [SMALL_STATE(28)] = 1170,
  [SMALL_STATE(29)] = 1224,
  [SMALL_STATE(30)] = 1260,
  [SMALL_STATE(31)] = 1314,
  [SMALL_STATE(32)] = 1368,
  [SMALL_STATE(33)] = 1404,
  [SMALL_STATE(34)] = 1458,
  [SMALL_STATE(35)] = 1512,
  [SMALL_STATE(36)] = 1566,
  [SMALL_STATE(37)] = 1594,
  [SMALL_STATE(38)] = 1648,
  [SMALL_STATE(39)] = 1676,
  [SMALL_STATE(40)] = 1704,
  [SMALL_STATE(41)] = 1758,
  [SMALL_STATE(42)] = 1786,
  [SMALL_STATE(43)] = 1814,
  [SMALL_STATE(44)] = 1842,
  [SMALL_STATE(45)] = 1896,
  [SMALL_STATE(46)] = 1924,
  [SMALL_STATE(47)] = 1956,
  [SMALL_STATE(48)] = 2010,
  [SMALL_STATE(49)] = 2038,
  [SMALL_STATE(50)] = 2062,
  [SMALL_STATE(51)] = 2098,
  [SMALL_STATE(52)] = 2130,
  [SMALL_STATE(53)] = 2166,
  [SMALL_STATE(54)] = 2202,
  [SMALL_STATE(55)] = 2233,
  [SMALL_STATE(56)] = 2263,
  [SMALL_STATE(57)] = 2293,
  [SMALL_STATE(58)] = 2323,
  [SMALL_STATE(59)] = 2353,
  [SMALL_STATE(60)] = 2383,
  [SMALL_STATE(61)] = 2413,
  [SMALL_STATE(62)] = 2443,
  [SMALL_STATE(63)] = 2473,
  [SMALL_STATE(64)] = 2503,
  [SMALL_STATE(65)] = 2533,
  [SMALL_STATE(66)] = 2563,
  [SMALL_STATE(67)] = 2593,
  [SMALL_STATE(68)] = 2616,
  [SMALL_STATE(69)] = 2639,
  [SMALL_STATE(70)] = 2662,
  [SMALL_STATE(71)] = 2685,
  [SMALL_STATE(72)] = 2708,
  [SMALL_STATE(73)] = 2720,
  [SMALL_STATE(74)] = 2736,
  [SMALL_STATE(75)] = 2752,
  [SMALL_STATE(76)] = 2764,
  [SMALL_STATE(77)] = 2780,
  [SMALL_STATE(78)] = 2796,
  [SMALL_STATE(79)] = 2812,
  [SMALL_STATE(80)] = 2825,
  [SMALL_STATE(81)] = 2838,
  [SMALL_STATE(82)] = 2851,
  [SMALL_STATE(83)] = 2864,
  [SMALL_STATE(84)] = 2877,
  [SMALL_STATE(85)] = 2890,
  [SMALL_STATE(86)] = 2903,
  [SMALL_STATE(87)] = 2916,
  [SMALL_STATE(88)] = 2929,
  [SMALL_STATE(89)] = 2942,
  [SMALL_STATE(90)] = 2955,
  [SMALL_STATE(91)] = 2968,
  [SMALL_STATE(92)] = 2981,
  [SMALL_STATE(93)] = 2991,
  [SMALL_STATE(94)] = 2999,
  [SMALL_STATE(95)] = 3007,
  [SMALL_STATE(96)] = 3017,
  [SMALL_STATE(97)] = 3025,
  [SMALL_STATE(98)] = 3033,
  [SMALL_STATE(99)] = 3041,
  [SMALL_STATE(100)] = 3051,
  [SMALL_STATE(101)] = 3058,
  [SMALL_STATE(102)] = 3065,
  [SMALL_STATE(103)] = 3072,
  [SMALL_STATE(104)] = 3079,
  [SMALL_STATE(105)] = 3086,
  [SMALL_STATE(106)] = 3093,
  [SMALL_STATE(107)] = 3100,
  [SMALL_STATE(108)] = 3107,
  [SMALL_STATE(109)] = 3114,
  [SMALL_STATE(110)] = 3121,
  [SMALL_STATE(111)] = 3128,
  [SMALL_STATE(112)] = 3135,
  [SMALL_STATE(113)] = 3142,
  [SMALL_STATE(114)] = 3149,
  [SMALL_STATE(115)] = 3156,
  [SMALL_STATE(116)] = 3163,
  [SMALL_STATE(117)] = 3170,
  [SMALL_STATE(118)] = 3177,
  [SMALL_STATE(119)] = 3184,
  [SMALL_STATE(120)] = 3191,
  [SMALL_STATE(121)] = 3198,
  [SMALL_STATE(122)] = 3205,
  [SMALL_STATE(123)] = 3212,
  [SMALL_STATE(124)] = 3219,
  [SMALL_STATE(125)] = 3226,
  [SMALL_STATE(126)] = 3233,
  [SMALL_STATE(127)] = 3240,
  [SMALL_STATE(128)] = 3247,
  [SMALL_STATE(129)] = 3254,
  [SMALL_STATE(130)] = 3261,
  [SMALL_STATE(131)] = 3268,
  [SMALL_STATE(132)] = 3275,
  [SMALL_STATE(133)] = 3282,
  [SMALL_STATE(134)] = 3289,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [9] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(4),
  [12] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(33),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(34),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(35),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(109),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(37),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(37),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(38),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(76),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(40),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(38),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(108),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 7),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 7),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 6, .production_id = 2),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 6, .production_id = 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 3, .production_id = 1),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functionCall, 3, .production_id = 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 8, .production_id = 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 8, .production_id = 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 5, .production_id = 2),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 5, .production_id = 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 5),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 5),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 4, .production_id = 1),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functionCall, 4, .production_id = 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 5, .production_id = 1),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functionCall, 5, .production_id = 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 7, .production_id = 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 7, .production_id = 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 7, .production_id = 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 7, .production_id = 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dispatch, 9, .production_id = 3),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dispatch, 9, .production_id = 3),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dispatch_repeat1, 2),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_classDefine_repeat1, 2), SHIFT_REPEAT(95),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_classDefine_repeat1, 2),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal, 3),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat2, 2), SHIFT_REPEAT(111),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat2, 2),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [230] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(130),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat3, 2), SHIFT_REPEAT(81),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat3, 2),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dispatch_repeat1, 2), SHIFT_REPEAT(10),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [245] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 2), SHIFT_REPEAT(99),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 2),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat2, 4),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classDefine, 7),
  [296] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [298] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [306] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classDefine, 6),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classDefine, 5),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 8, .production_id = 1),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 1),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 9, .production_id = 1),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classDefine, 4),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 10, .production_id = 1),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [346] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [348] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cool(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_id,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
